name: C Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        make -C examples -f ../Makefile

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: examples/app

    - name: Display Build Output
      uses: actions/github-script@v4
      with:
        script: |
          const artifacts = context.payload.workflow_run.artifacts_url;
          console.log(`Build artifacts are available for download at: ${artifacts}`);
