name: C Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        make -C examples -f ../Makefile

    - name: Display Build Output
      uses: actions/github-script@v4
      with:
        script: |
          const buildStatus = context.payload.workflow_run.status;
          console.log(`Build Status: ${buildStatus}`);
