name: C Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential

    - name: Build C code
      run: make -C src/

    - name: Run tests
      run: make -C tests/

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          src/build/
          tests/build/
