name: C/C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up C/C++ Compiler
      uses: actions/setup-cpp@v2
      with:
        cpp-version: '11'
        compiler: 'gcc'

    - name: Build
      run: |
        make -C examples
